# Generated by Django 5.1.1 on 2024-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_prato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prato',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('prato', 'Prato'), ('bebida', 'Bebida'), ('sobremesa', 'Sobremesa')], default='prato', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tempo_preparo',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo de preparo em minutos', null=True),
        ),
    ]
